[pytest]
testpaths = tests
filterwarnings =
    ignore:\s*on_event is deprecated:DeprecationWarning
    ignore:.*datetime.datetime.utcnow.*:DeprecationWarning
    ignore:.*anyio.abc.BlockingPortal.*:DeprecationWarning
